### ISSUE TITLE
Organize the repo in a better Way

### ISSUE THREAD

**Issue by tayalmanan28** [tayalmanan28/MuJoCo-Tutorial#1]
Proper organization of the repo means assembling the examples into one folder and accordingly edit the paths of the folder so that one can run the examples in a better way

**Comment by bchainbuidler** [comment]
Hi, I Have a good background in python can I contribute to the project?

**Comment by tayalmanan28** [comment]
Yea Sure all you have to do is to follow the instructions in the readme and start organizing the data

**Comment by bchainbuidler** [comment]
Ok Thanks so can you assign me to the issue?

**Comment by tayalmanan28** [comment]
Sure

**Comment by tayalmanan28** [comment]
Also Please update the README with the running instructions for the examples

**Comment by tayalmanan28** [comment]
Moreover, rename hello_world_mujoco_base.py to run.py and add one example to that file

**Comment by bchainbuidler** [comment]
Got it

**Comment by bchainbuidler** [comment]
Sir I have created a pull request, following all your instructions correctly.

**Comment by tayalmanan28** [comment]
ok let me go through the request and merge it if it is correct

**Comment by tayalmanan28** [comment]
I have merged the pull Request
