### ISSUE TITLE
Make a banner/logo for MuJoCo Tutorial

### ISSUE THREAD

**Issue by tayalmanan28** [tayalmanan28/MuJoCo-Tutorial#2]
Need someone to design a logo/banner for the repository.

**Comment by Guillergood** [comment]
I can try this one. Please assign this to me 😄

**Comment by tayalmanan28** [comment]
Sure

**Comment by Guillergood** [comment]
Can you provide more information about the logo? (Any special color/colors, object, form, which file extension...). Thanks in advance

**Comment by tayalmanan28** [comment]
Probably something like Orange or blue in the svg format
